# Generated by Django 4.2.6 on 2024-12-12 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.TextField()),
                ('mjesto', models.TextField()),
                ('dob', models.IntegerField()),
                ('vip', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Oglas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predmet', models.CharField(max_length=100)),
                ('mjesto', models.TextField()),
                ('cijena', models.IntegerField()),
                ('razmjena', models.BooleanField()),
                ('prodavatelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.korisnik')),
            ],
        ),
    ]
