# Generated by Django 4.2.6 on 2024-12-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='prezime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='oglas',
            name='mjesto',
            field=models.CharField(max_length=100),
        ),
    ]
