# Generated by Django 4.2.6 on 2024-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_korisnik_prezime_alter_oglas_mjesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnik',
            name='mjesto',
            field=models.CharField(max_length=100),
        ),
    ]
